language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
script: 
  - pymavlink/generator/mavgen.py --lang='Python' 	--output=/tmp/ message_definitions/v1.0/common.xml
  - pymavlink/generator/mavgen.py --lang='C' 		--output=/tmp/ message_definitions/v1.0/common.xml
  - pymavlink/generator/mavgen.py --lang='CS' 		--output=/tmp/ message_definitions/v1.0/common.xml
  - pymavlink/generator/mavgen.py --lang='WLua' 	--output=/tmp/ message_definitions/v1.0/common.xml

